server:
  port: 8080

spring:
  application:
    name: bibei-backend
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/bibei;MODE=MySQL;AUTO_SERVER=TRUE
    username: sa
    password:
  sql:
    init:
      mode: always
      encoding: UTF-8
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.bibei: info
